<?php

// this file is automatically generated by kickass-libexec scripts...

// you can change the name but not the code...
define( 'LX_NAME', 'Kickass Libexec' );
define( 'LX_CODE', 'lx' );

//define( 'LX_VERSION', '0.1.293' );
define( 'LX_VERSION_MAJOR', 0 );
define( 'LX_VERSION_MINOR', 1 );
define( 'LX_VERSION_PATCH', 293 );

define(
  'LX_SVN_DATE',
  '$Date: 2024-08-10 00:19:50 +0000 (Sat, 10 Aug 2024) $'
);
define( 'LX_SVN_REVISION', '$Revision: 249682324 $' );
define( 'LX_SVN_AUTHOR', '$Author: jj5 $' );

define( 'LX_GIT_DATE', '2024-08-10 00:19:50 +0000 (Sat, 10 Aug 2024)' );
