<?php

// this file is automatically generated by kickass-libexec scripts...

// you can change the name but not the code...
define( 'LX_NAME', 'Kickass Libexec' );
define( 'LX_CODE', 'lx' );

//define( 'LX_VERSION', '0.1.407' );
define( 'LX_VERSION_MAJOR', 0 );
define( 'LX_VERSION_MINOR', 1 );
define( 'LX_VERSION_PATCH', 407 );

define(
  'LX_SVN_DATE',
  '$Date: 2026-01-25 20:06:07 +0000 (Sun, 25 Jan 2026) $'
);
define( 'LX_SVN_REVISION', '$Revision: 58862038 $' );
define( 'LX_SVN_AUTHOR', '$Author: jj5 $' );

define( 'LX_GIT_DATE', '2026-01-25 20:06:07 +0000 (Sun, 25 Jan 2026)' );
