#!/bin/bash

# this file is automatically generated by kickass-libexec scripts...

export LX_NAME='lx-0.1';
export LX_CODE='lx';

export LX_VERSION='0.1.437';
export LX_VERSION_MAJOR='0';
export LX_VERSION_MINOR='1';
export LX_VERSION_PATCH='437';

export LX_SVN_DATE='Date: 2026-05-04 09:34:57 +0000 (Mon, 04 May 2026)';
export LX_SVN_REVISION='Revision: 104120542';
export LX_SVN_AUTHOR='Author: jj5';

export LX_GIT_DATE='2026-05-04 09:34:57 +0000 (Mon, 04 May 2026)';
