#!/bin/bash

# this file is automatically generated by kickass-libexec scripts...

export LX_NAME='Kickass Libexec';
export LX_CODE='lx';

export LX_VERSION='0.1.391';
export LX_VERSION_MAJOR='0';
export LX_VERSION_MINOR='1';
export LX_VERSION_PATCH='391';

export LX_SVN_DATE='Date: 2025-07-08 13:41:06 +1000 (Tue, 08 Jul 2025)';
export LX_SVN_REVISION='Revision: 64457742';
export LX_SVN_AUTHOR='Author: jj5';

export LX_GIT_DATE='2025-07-08 13:41:06 +1000 (Tue, 08 Jul 2025)';
