#!/bin/bash

# this file is automatically generated by kickass-libexec scripts...

export LX_NAME='Kickass Libexec';
export LX_CODE='lx';

export LX_VERSION='0.1.421';
export LX_VERSION_MAJOR='0';
export LX_VERSION_MINOR='1';
export LX_VERSION_PATCH='421';

export LX_SVN_DATE='Date: 2026-04-06 18:08:50 +1000 (Mon, 06 Apr 2026)';
export LX_SVN_REVISION='Revision: 84039464';
export LX_SVN_AUTHOR='Author: jj5';

export LX_GIT_DATE='2026-04-06 18:08:50 +1000 (Mon, 06 Apr 2026)';
