#!/bin/bash

lx_gen_standard() {

  local project="${1:-}";
  local version="${2:-}";

  lx_ensure 1 'project' "$project";
  lx_ensure 2 'version' "$version";

  local uppercase_project="${project^^}";

  local version_major="${version%.*}";
  local version_minor="${version##*.}";

  export LX_PROJECT_CODE="${uppercase_project//-/_}";

  lx_run lx_gen_standard_gitignore;

  lx_run mkdir -p 'inc';

  lx_run lx_gen_standard_inc_version_php;
  lx_run lx_gen_standard_inc_version_sh;

}

lx_gen_standard_gitignore() {

  [ -f '.gitignore' ] && { return; }

  cat <<EOF > .gitignore
/.vscode/
/.phpdoc/
/build/
/etc/local/
/log/
/nbproject/
/var/
/vendor/
/config.php
/debug.php
EOF

}

lx_gen_standard_inc_version_php() {

  local file='inc/version.php';

  [ -f "$file" ] && { return; }

  cat <<EOF > $file
<?php

// this file is automatically generated by kickass-libexec scripts...

// you can change the name but not the code...
define( '${LX_PROJECT_CODE}_NAME', '${project}' );
define( '${LX_PROJECT_CODE}_CODE', '${project}' );

define( '${LX_PROJECT_CODE}_VERSION_MAJOR', $version_major );
define( '${LX_PROJECT_CODE}_VERSION_MINOR', $version_minor );
define( '${LX_PROJECT_CODE}_VERSION_PATCH', 1 );

define(
  '${LX_PROJECT_CODE}_SVN_DATE',
  '\$Date: $( date +"%Y-%m-%d %H:%M:%S %z (%a, %d %b %Y)" ) $'
);
define( '${LX_PROJECT_CODE}_SVN_REVISION', '\$Revision: 1 $' );
define( '${LX_PROJECT_CODE}_SVN_AUTHOR', '\$Author: $LX_VCS_USER $' );

define( '${LX_PROJECT_CODE}_GIT_DATE', '$( date +"%Y-%m-%d %H:%M:%S %z (%a, %d %b %Y)" )' );
EOF

}

lx_gen_standard_inc_version_sh() {

  local file='inc/version.sh';

  [ -f "$file" ] && { return; }

  cat <<EOF > $file
#!/bin/bash

# this file will be automatically generated by kickass-libexec scripts...

EOF

}
